### ISSUE TITLE
increase translator velocity

### ISSUE THREAD

**Issue by johnfelipe** [giovanni-bertoncelli/json-translator#2]
https://www.ibm.com/demos/live/watson-language-translator/self-service/home

json with 2159 lines translate in 32 sec, but in same time with your app only translate 97 lines
how can enhance velocity for this matter?

**Comment by HighSoftWare96** [comment]
I do not know if it can be enhanced since the repo is using the API and therd can probably be some restrictions on the speed and the usage of the API... Maybe there are some IBM subscriptions with more speed?

**Comment by johnfelipe** [comment]
How can ehanced speed
I'm using subscription, but online demo is more speedy
